### PR TITLE
Multi-realm Updates

### PR DESCRIPTION
**Pull request by mstumpfx**
A new realm config option that fills in the endpoint URLs automatically, and also doc changes.

### CODE REVIEW

**Comment by keitwb** [comment]
This should not be merged until the alias for us0 gets activated (it was not as of now).

**Comment by mstumpfx** [comment]
@keitwb should we update the installer script to pass through the realmConfig option instead of using ingest and api urls?

**Comment by keitwb** [comment]
Yeah that's a good idea.

**Comment by mstumpfx** [comment]
@keitwb multi-realm API endpoints are live so this is good to go

**Pull request merged**
