### PR TITLE
Allow user to monitor specific regions

### PR DESCRIPTION
**Pull request by dloucasfx**
Signed-off-by: Dani Louca <dlouca@splunk.com>

### CODE REVIEW

**Review by keitwb — APPROVED** [review]

**Comment by rmfitzpatrick** [comment]
The test failure looks relevant but I've not been able to get a sense of what's wrong when briefly walking the logs:

```
time="2021-08-18T18:09:49Z" level=error msg="Failed to authenticate Openstack client due to Invalid client version '2.0'. Major part should be '3'" createdTime=1.6293101898679285e+09 lineno=96 logger=root monitorID=1 monitorType=collectd/openstack runnerPID=4834 sourcePath=/home/circleci/project/bundle/collectd-python/openstack/openstack_metrics.py
<...>
time="2021-08-18T18:20:55Z" level=error msg="Failed to fetch Openstack metrics due to 'cinder'" createdTime=1.6293108554690814e+09 lineno=139 logger=root monitorID=1 monitorType=collectd/openstack runnerPID=25119 sourcePath=/home/circleci/project/bundle/collectd-python/openstack/openstack_metrics.py
<...>
time="2021-08-18T18:30:31Z" level=error msg="Failed to fetch Openstack metrics due to 'cinder'" createdTime=1.6293114314832914e+09 lineno=139 logger=root monitorID=1 monitorType=collectd/openstack runnerPID=10424 sourcePath=/home/circleci/project/bundle/collectd-python/openstack/openstack_metrics.py

```

**Comment by dloucasfx** [comment]
yeah, I am looking into it, but having the same issue as the standalone test works fine for me and running the test locally fails to setup the openstack test environment....
I will keep digging

**Comment by dloucasfx** [comment]
ok, I am seeing some unhelpful error coming from the plugin which is causing the metrics not to come through...
````
ERRO[0012] Failed to fetch Openstack metrics due to 'cinder'  createdTime=1.6293166850624595e+09 lineno=140 logger=root monitorID=1 monitorType=collectd/openstack runnerPID=9425 sourcePath=/bundle/collectd-python/openstack/openstack_metrics.py
````

**Comment by dloucasfx** [comment]
So here is what happened.
The openstack plugin requirement is not versioned https://github.com/signalfx/collectd-openstack/blob/master/requirements.txt

When I implemented and tested my openstack plugin fix, I used a month old SA dev image, which had the `python-cinderclient` module before this change https://github.com/openstack/python-cinderclient/commit/3502a5591a654ae57741c6738994ffa9d8457696

With the new build, we are now pulling the latest `python-cinderclient` which no longer support v2 (see linked PR).
This issue is a ticking bomb and was just a matter of time before we hit it.

Anyway, the fix need to be in the plugin to address this error. (same apply to the neutron module)
````
ERRO[0009] Failed to authenticate Openstack client due to Invalid client version '2.0'. Major part should be '3'  createdTime=1.6293322102797165e+09 lineno=96 logger=root monitorID=1 monitorType=collectd/openstack runnerPID=30 sourcePath=/bundle/collectd-python/openstack/openstack_metrics.py
````

I am actually going to test using an older version, it's safer as it won't require extensive testing

**Comment by dloucasfx** [comment]
This is blocked by this fix https://github.com/signalfx/collectd-openstack/pull/8

**Review by jcheng-splunk — APPROVED** [review]

**Review by tmorrisonsfx — APPROVED** [review]

**Pull request merged**
