### PR TITLE
Add kubernetes `updated` datapoint to DaemonSet and Deployment

### LINKED ISSUE #1318: Add kubernetes "updated" datapoint to DaemonSet, Deployment
Currently, the kubernetes monitor provides _available_/_desired_ status datapoints for DaemonSet and Deployment resources:

https://github.com/signalfx/signalfx-agent/blob/v5.1.6/pkg/monitors/kubernetes/cluster/metrics/daemonsets.go#L21-L46

https://github.com/signalfx/signalfx-agent/blob/v5.1.6/pkg/monitors/kubernetes/cluster/metrics/deployments.go#L26-L27

It would be useful to also expose the _updated_ status of these resources:

- DaemonSet: `UpdatedNumberScheduled` https://github.com/kubernetes/api/blob/kubernetes-1.18.2/apps/v1/types.go#L566
- Deployment: `UpdatedReplicas` https://github.com/kubernetes/api/blob/kubernetes-1.18.2/apps/v1/types.go#L387

This would allow to detect stuck deployments where `updated` is lower than `desired` for too long periods.

Note: StatefulSet already exposes `UpdatedReplicas` as `kubernetes.stateful_set.updated`, see https://github.com/signalfx/signalfx-agent/blob/v5.1.6/pkg/monitors/kubernetes/cluster/metrics/statefulsets.go#L45-L50

### PR DESCRIPTION
**Pull request by pdecat**
Resolve #1318

### CODE REVIEW

**Comment by keitwb** [comment]
Hi @pdecat, thanks for submitting this.  I added some updates for the docs and tests, and also used the constants from the generated metadata file for the metric names (something we are trying to do consistently in all monitors, at least for new stuff).

**Comment by keitwb** [comment]
Note that these new metrics will be categorized as "non-default", so you will have to use the `extraMetrics` config on the `kubernetes-cluster` monitor to get them to be emitted from the agent.

**Comment by pdecat** [comment]
Hi @keitwb, thanks for taking on this PR so quicky and adding the missing pieces!

> Note that these new metrics will be categorized as "non-default", so you will have to use the `extraMetrics` config on the `kubernetes-cluster` monitor to get them to be emitted from the agent.

Oh, that explains why I didn't see the `kubernetes.stateful_set.updated`.

**Comment by pdecat** [comment]
This is working perfectly (tested with agent v5.2.1), thanks @keitwb!

**Pull request merged**
