### PR TITLE
Added securityContext for deployment and daemonset.

### PR DESCRIPTION
**Pull request by chungktran**
I needed the ability to add securityContext into deployment and daemonset that isn't available in current helm chart.

### CODE REVIEW

**Comment by keitwb** [comment]
@chungktran can you run the `./deployments/k8s/generate-from-helm` script and push the changes to this PR?

**Comment by chungktran** [comment]
> @chungktran can you run the `./deployments/k8s/generate-from-helm` script and push the changes to this PR?

Line 20 in `https://github.com/signalfx/signalfx-agent/blob/master/deployments/k8s/generate-from-helm#L20` needs to be removed for that script to run successfully. Below is the output.

```
+++ dirname ./deployments/k8s/generate-from-helm
++ cd ./deployments/k8s
++ pwd
+ SCRIPT_DIR=/home/ctran/signalfx-agent/deployments/k8s
+ AGENT_CHART_DIR=/home/ctran/signalfx-agent/deployments/k8s/helm/signalfx-agent
++ /home/ctran/signalfx-agent/deployments/k8s/../../scripts/latest-final-release
+ AGENT_RELEASE_VERSION=5.7.2
++ mktemp -d
+ tmpdir=/tmp/tmp.9saWdUN6cG
+ trap 'rm -rf /tmp/tmp.9saWdUN6cG' EXIT
+ render /home/ctran/signalfx-agent/deployments/k8s false
+ local outdir=/home/ctran/signalfx-agent/deployments/k8s
+ local isServerless=false
+ helm template --namespace signalfx-agent --set signalFxAccessToken=MY_TOKEN --set clusterName=MY-CLUSTER --set fullnameOverride=signalfx-agent --set agentVersion=5.7.2 --set isServerless=false --output-dir /tmp/tmp.9saWdUN6cG /home/ctran/signalfx-agent/deployments/k8s/helm/signalfx-agent
wrote /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/secrets.yaml
wrote /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/configmap.yaml
wrote /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/serviceaccount.yaml
wrote /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/clusterrole.yaml
wrote /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/clusterrolebinding.yaml
wrote /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/configmap-role.yaml
wrote /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/configmap-rolebinding.yaml
wrote /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/daemonset.yaml
wrote /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/deployment.yaml
+ templates='configmap.yaml daemonset.yaml deployment.yaml clusterrole.yaml clusterrolebinding.yaml serviceaccount.yaml configmap-role.yaml configmap-rolebinding.yaml'
+ for f in $templates
+ fullpath=/tmp/tmp.9saWdUN6cG/signalfx-agent/templates/configmap.yaml
+ [[ configmap.yaml == \d\a\e\m\o\n\s\e\t\.\y\a\m\l ]]
+ [[ configmap.yaml == \d\e\p\l\o\y\m\e\n\t\.\y\a\m\l ]]
+ [[ configmap.yaml == \c\o\n\f\i\g\m\a\p\-\r\o\l\e\.\y\a\m\l ]]
+ [[ configmap.yaml == \c\o\n\f\i\g\m\a\p\-\r\o\l\e\b\i\n\d\i\n\g\.\y\a\m\l ]]
+ cat /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/configmap.yaml
+ sed -e 's/[[:space:]]*$//'
+ grep -v 'chart: signalfx-agent'
+ grep -v 'namespace: signalfx-agent'
+ grep -v 'heritage: Helm'
+ grep -iv 'release: signalfx-agent'
+ echo 'Wrote resource configmap.yaml'
Wrote resource configmap.yaml
+ for f in $templates
+ fullpath=/tmp/tmp.9saWdUN6cG/signalfx-agent/templates/daemonset.yaml
+ [[ daemonset.yaml == \d\a\e\m\o\n\s\e\t\.\y\a\m\l ]]
+ [[ false == \t\r\u\e ]]
+ [[ daemonset.yaml == \d\e\p\l\o\y\m\e\n\t\.\y\a\m\l ]]
+ [[ daemonset.yaml == \c\o\n\f\i\g\m\a\p\-\r\o\l\e\.\y\a\m\l ]]
+ [[ daemonset.yaml == \c\o\n\f\i\g\m\a\p\-\r\o\l\e\b\i\n\d\i\n\g\.\y\a\m\l ]]
+ cat /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/daemonset.yaml
+ sed -e 's/[[:space:]]*$//'
+ grep -v 'chart: signalfx-agent'
+ grep -v 'namespace: signalfx-agent'
+ grep -v 'heritage: Helm'
+ grep -iv 'release: signalfx-agent'
+ echo 'Wrote resource daemonset.yaml'
Wrote resource daemonset.yaml
+ for f in $templates
+ fullpath=/tmp/tmp.9saWdUN6cG/signalfx-agent/templates/deployment.yaml
+ [[ deployment.yaml == \d\a\e\m\o\n\s\e\t\.\y\a\m\l ]]
+ [[ deployment.yaml == \d\e\p\l\o\y\m\e\n\t\.\y\a\m\l ]]
+ [[ false == \f\a\l\s\e ]]
+ continue
+ for f in $templates
+ fullpath=/tmp/tmp.9saWdUN6cG/signalfx-agent/templates/clusterrole.yaml
+ [[ clusterrole.yaml == \d\a\e\m\o\n\s\e\t\.\y\a\m\l ]]
+ [[ clusterrole.yaml == \d\e\p\l\o\y\m\e\n\t\.\y\a\m\l ]]
+ [[ clusterrole.yaml == \c\o\n\f\i\g\m\a\p\-\r\o\l\e\.\y\a\m\l ]]
+ [[ clusterrole.yaml == \c\o\n\f\i\g\m\a\p\-\r\o\l\e\b\i\n\d\i\n\g\.\y\a\m\l ]]
+ cat /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/clusterrole.yaml
+ sed -e 's/[[:space:]]*$//'
+ grep -v 'chart: signalfx-agent'
+ grep -v 'namespace: signalfx-agent'
+ grep -v 'heritage: Helm'
+ grep -iv 'release: signalfx-agent'
+ echo 'Wrote resource clusterrole.yaml'
Wrote resource clusterrole.yaml
+ for f in $templates
+ fullpath=/tmp/tmp.9saWdUN6cG/signalfx-agent/templates/clusterrolebinding.yaml
+ [[ clusterrolebinding.yaml == \d\a\e\m\o\n\s\e\t\.\y\a\m\l ]]
+ [[ clusterrolebinding.yaml == \d\e\p\l\o\y\m\e\n\t\.\y\a\m\l ]]
+ [[ clusterrolebinding.yaml == \c\o\n\f\i\g\m\a\p\-\r\o\l\e\.\y\a\m\l ]]
+ [[ clusterrolebinding.yaml == \c\o\n\f\i\g\m\a\p\-\r\o\l\e\b\i\n\d\i\n\g\.\y\a\m\l ]]
+ cat /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/clusterrolebinding.yaml
+ sed -e 's/[[:space:]]*$//'
+ grep -v 'chart: signalfx-agent'
+ grep -v 'namespace: signalfx-agent'
+ grep -v 'heritage: Helm'
+ grep -iv 'release: signalfx-agent'
+ echo 'Wrote resource clusterrolebinding.yaml'
Wrote resource clusterrolebinding.yaml
+ for f in $templates
+ fullpath=/tmp/tmp.9saWdUN6cG/signalfx-agent/templates/serviceaccount.yaml
+ [[ serviceaccount.yaml == \d\a\e\m\o\n\s\e\t\.\y\a\m\l ]]
+ [[ serviceaccount.yaml == \d\e\p\l\o\y\m\e\n\t\.\y\a\m\l ]]
+ [[ serviceaccount.yaml == \c\o\n\f\i\g\m\a\p\-\r\o\l\e\.\y\a\m\l ]]
+ [[ serviceaccount.yaml == \c\o\n\f\i\g\m\a\p\-\r\o\l\e\b\i\n\d\i\n\g\.\y\a\m\l ]]
+ cat /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/serviceaccount.yaml
+ sed -e 's/[[:space:]]*$//'
+ grep -v 'chart: signalfx-agent'
+ grep -v 'namespace: signalfx-agent'
+ grep -v 'heritage: Helm'
+ grep -iv 'release: signalfx-agent'
+ echo 'Wrote resource serviceaccount.yaml'
Wrote resource serviceaccount.yaml
+ for f in $templates
+ fullpath=/tmp/tmp.9saWdUN6cG/signalfx-agent/templates/configmap-role.yaml
+ [[ configmap-role.yaml == \d\a\e\m\o\n\s\e\t\.\y\a\m\l ]]
+ [[ configmap-role.yaml == \d\e\p\l\o\y\m\e\n\t\.\y\a\m\l ]]
+ [[ configmap-role.yaml == \c\o\n\f\i\g\m\a\p\-\r\o\l\e\.\y\a\m\l ]]
+ cat /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/configmap-role.yaml
+ sed -e 's/namespace: signalfx-agent/namespace: MY_AGENT_NAMESPACE/' -e 's/[[:space:]]*$//'
+ grep -v 'chart: signalfx-agent'
+ grep -v 'heritage: Helm'
+ grep -iv 'release: signalfx-agent'
+ continue
+ for f in $templates
+ fullpath=/tmp/tmp.9saWdUN6cG/signalfx-agent/templates/configmap-rolebinding.yaml
+ [[ configmap-rolebinding.yaml == \d\a\e\m\o\n\s\e\t\.\y\a\m\l ]]
+ [[ configmap-rolebinding.yaml == \d\e\p\l\o\y\m\e\n\t\.\y\a\m\l ]]
+ [[ configmap-rolebinding.yaml == \c\o\n\f\i\g\m\a\p\-\r\o\l\e\.\y\a\m\l ]]
+ [[ configmap-rolebinding.yaml == \c\o\n\f\i\g\m\a\p\-\r\o\l\e\b\i\n\d\i\n\g\.\y\a\m\l ]]
+ cat /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/configmap-rolebinding.yaml
+ sed -e 's/namespace: signalfx-agent/namespace: MY_AGENT_NAMESPACE/' -e 's/[[:space:]]*$//'
+ grep -v 'chart: signalfx-agent'
+ grep -v 'heritage: Helm'
+ grep -iv 'release: signalfx-agent'
+ continue
+ echo '  namespace: MY_AGENT_NAMESPACE'
+ rm -rf /tmp/tmp.9saWdUN6cG/signalfx-agent
+ render /home/ctran/signalfx-agent/deployments/k8s/serverless true
+ local outdir=/home/ctran/signalfx-agent/deployments/k8s/serverless
+ local isServerless=true
+ helm template --namespace signalfx-agent --set signalFxAccessToken=MY_TOKEN --set clusterName=MY-CLUSTER --set fullnameOverride=signalfx-agent --set agentVersion=5.7.2 --set isServerless=true --output-dir /tmp/tmp.9saWdUN6cG /home/ctran/signalfx-agent/deployments/k8s/helm/signalfx-agent
wrote /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/secrets.yaml
wrote /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/configmap.yaml
wrote /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/serviceaccount.yaml
wrote /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/clusterrole.yaml
wrote /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/clusterrolebinding.yaml
wrote /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/configmap-role.yaml
wrote /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/configmap-rolebinding.yaml
wrote /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/deployment.yaml
+ templates='configmap.yaml daemonset.yaml deployment.yaml clusterrole.yaml clusterrolebinding.yaml serviceaccount.yaml configmap-role.yaml configmap-rolebinding.yaml'
+ for f in $templates
+ fullpath=/tmp/tmp.9saWdUN6cG/signalfx-agent/templates/configmap.yaml
+ [[ configmap.yaml == \d\a\e\m\o\n\s\e\t\.\y\a\m\l ]]
+ [[ configmap.yaml == \d\e\p\l\o\y\m\e\n\t\.\y\a\m\l ]]
+ [[ configmap.yaml == \c\o\n\f\i\g\m\a\p\-\r\o\l\e\.\y\a\m\l ]]
+ [[ configmap.yaml == \c\o\n\f\i\g\m\a\p\-\r\o\l\e\b\i\n\d\i\n\g\.\y\a\m\l ]]
+ cat /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/configmap.yaml
+ sed -e 's/[[:space:]]*$//'
+ grep -v 'namespace: signalfx-agent'
+ grep -v 'chart: signalfx-agent'
+ grep -v 'heritage: Helm'
+ grep -iv 'release: signalfx-agent'
+ echo 'Wrote resource configmap.yaml'
Wrote resource configmap.yaml
+ for f in $templates
+ fullpath=/tmp/tmp.9saWdUN6cG/signalfx-agent/templates/daemonset.yaml
+ [[ daemonset.yaml == \d\a\e\m\o\n\s\e\t\.\y\a\m\l ]]
+ [[ true == \t\r\u\e ]]
+ continue
+ for f in $templates
+ fullpath=/tmp/tmp.9saWdUN6cG/signalfx-agent/templates/deployment.yaml
+ [[ deployment.yaml == \d\a\e\m\o\n\s\e\t\.\y\a\m\l ]]
+ [[ deployment.yaml == \d\e\p\l\o\y\m\e\n\t\.\y\a\m\l ]]
+ [[ true == \f\a\l\s\e ]]
+ [[ deployment.yaml == \c\o\n\f\i\g\m\a\p\-\r\o\l\e\.\y\a\m\l ]]
+ [[ deployment.yaml == \c\o\n\f\i\g\m\a\p\-\r\o\l\e\b\i\n\d\i\n\g\.\y\a\m\l ]]
+ cat /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/deployment.yaml
+ sed -e 's/[[:space:]]*$//'
+ grep -v 'chart: signalfx-agent'
+ grep -v 'namespace: signalfx-agent'
+ grep -iv 'release: signalfx-agent'
+ grep -v 'heritage: Helm'
+ echo 'Wrote resource deployment.yaml'
Wrote resource deployment.yaml
+ for f in $templates
+ fullpath=/tmp/tmp.9saWdUN6cG/signalfx-agent/templates/clusterrole.yaml
+ [[ clusterrole.yaml == \d\a\e\m\o\n\s\e\t\.\y\a\m\l ]]
+ [[ clusterrole.yaml == \d\e\p\l\o\y\m\e\n\t\.\y\a\m\l ]]
+ [[ clusterrole.yaml == \c\o\n\f\i\g\m\a\p\-\r\o\l\e\.\y\a\m\l ]]
+ [[ clusterrole.yaml == \c\o\n\f\i\g\m\a\p\-\r\o\l\e\b\i\n\d\i\n\g\.\y\a\m\l ]]
+ cat /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/clusterrole.yaml
+ sed -e 's/[[:space:]]*$//'
+ grep -v 'namespace: signalfx-agent'
+ grep -v 'chart: signalfx-agent'
+ grep -v 'heritage: Helm'
+ grep -iv 'release: signalfx-agent'
+ echo 'Wrote resource clusterrole.yaml'
Wrote resource clusterrole.yaml
+ for f in $templates
+ fullpath=/tmp/tmp.9saWdUN6cG/signalfx-agent/templates/clusterrolebinding.yaml
+ [[ clusterrolebinding.yaml == \d\a\e\m\o\n\s\e\t\.\y\a\m\l ]]
+ [[ clusterrolebinding.yaml == \d\e\p\l\o\y\m\e\n\t\.\y\a\m\l ]]
+ [[ clusterrolebinding.yaml == \c\o\n\f\i\g\m\a\p\-\r\o\l\e\.\y\a\m\l ]]
+ [[ clusterrolebinding.yaml == \c\o\n\f\i\g\m\a\p\-\r\o\l\e\b\i\n\d\i\n\g\.\y\a\m\l ]]
+ cat /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/clusterrolebinding.yaml
+ sed -e 's/[[:space:]]*$//'
+ grep -v 'chart: signalfx-agent'
+ grep -v 'namespace: signalfx-agent'
+ grep -iv 'release: signalfx-agent'
+ grep -v 'heritage: Helm'
+ echo 'Wrote resource clusterrolebinding.yaml'
Wrote resource clusterrolebinding.yaml
+ for f in $templates
+ fullpath=/tmp/tmp.9saWdUN6cG/signalfx-agent/templates/serviceaccount.yaml
+ [[ serviceaccount.yaml == \d\a\e\m\o\n\s\e\t\.\y\a\m\l ]]
+ [[ serviceaccount.yaml == \d\e\p\l\o\y\m\e\n\t\.\y\a\m\l ]]
+ [[ serviceaccount.yaml == \c\o\n\f\i\g\m\a\p\-\r\o\l\e\.\y\a\m\l ]]
+ [[ serviceaccount.yaml == \c\o\n\f\i\g\m\a\p\-\r\o\l\e\b\i\n\d\i\n\g\.\y\a\m\l ]]
+ cat /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/serviceaccount.yaml
+ sed -e 's/[[:space:]]*$//'
+ grep -v 'namespace: signalfx-agent'
+ grep -v 'chart: signalfx-agent'
+ grep -v 'heritage: Helm'
+ grep -iv 'release: signalfx-agent'
+ echo 'Wrote resource serviceaccount.yaml'
Wrote resource serviceaccount.yaml
+ for f in $templates
+ fullpath=/tmp/tmp.9saWdUN6cG/signalfx-agent/templates/configmap-role.yaml
+ [[ configmap-role.yaml == \d\a\e\m\o\n\s\e\t\.\y\a\m\l ]]
+ [[ configmap-role.yaml == \d\e\p\l\o\y\m\e\n\t\.\y\a\m\l ]]
+ [[ configmap-role.yaml == \c\o\n\f\i\g\m\a\p\-\r\o\l\e\.\y\a\m\l ]]
+ cat /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/configmap-role.yaml
+ sed -e 's/namespace: signalfx-agent/namespace: MY_AGENT_NAMESPACE/' -e 's/[[:space:]]*$//'
+ grep -v 'heritage: Helm'
+ grep -v 'chart: signalfx-agent'
+ grep -iv 'release: signalfx-agent'
+ continue
+ for f in $templates
+ fullpath=/tmp/tmp.9saWdUN6cG/signalfx-agent/templates/configmap-rolebinding.yaml
+ [[ configmap-rolebinding.yaml == \d\a\e\m\o\n\s\e\t\.\y\a\m\l ]]
+ [[ configmap-rolebinding.yaml == \d\e\p\l\o\y\m\e\n\t\.\y\a\m\l ]]
+ [[ configmap-rolebinding.yaml == \c\o\n\f\i\g\m\a\p\-\r\o\l\e\.\y\a\m\l ]]
+ [[ configmap-rolebinding.yaml == \c\o\n\f\i\g\m\a\p\-\r\o\l\e\b\i\n\d\i\n\g\.\y\a\m\l ]]
+ cat /tmp/tmp.9saWdUN6cG/signalfx-agent/templates/configmap-rolebinding.yaml
+ sed -e 's/namespace: signalfx-agent/namespace: MY_AGENT_NAMESPACE/' -e 's/[[:space:]]*$//'
+ grep -v 'heritage: Helm'
+ grep -v 'chart: signalfx-agent'
+ grep -iv 'release: signalfx-agent'
+ continue
+ echo '  namespace: MY_AGENT_NAMESPACE'
+ rm -rf /tmp/tmp.9saWdUN6cG/signalfx-agent
+ rm -rf /tmp/tmp.9saWdUN6cG
```

**Comment by keitwb** [comment]
ok, I don't understand why it needs to be removed.  I meant commit the changes to the repo in the pre-generated k8s resource files -- those are necessary to make the helm_check test pass.

**Comment by chungktran** [comment]
> ok, I don't understand why it needs to be removed. I meant commit the changes to the repo in the pre-generated k8s resource files -- those are necessary to make the helm_check test pass.

`helm template` command requires the path to the chart and it's specified as `$AGENT_CHART_DIR` on line 28 already so specify it on line 20 makes it not found.

**Comment by keitwb** [comment]
@chungktran see #1597.  I redid it with the chart regen.  Not sure why it is giving you issues.

**Comment by chungktran** [comment]
> @chungktran see #1597. I redid it with the chart regen. Not sure why it is giving you issues.

Below is the whole error output when I run that script.

```
$ pwd
/home/ctran/signalfx-agent
$ ./deployments/k8s/generate-from-helm
+++ dirname ./deployments/k8s/generate-from-helm
++ cd ./deployments/k8s
++ pwd
+ SCRIPT_DIR=/home/ctran/signalfx-agent/deployments/k8s
+ AGENT_CHART_DIR=/home/ctran/signalfx-agent/deployments/k8s/helm/signalfx-agent
++ /home/ctran/signalfx-agent/deployments/k8s/../../scripts/latest-final-release
+ AGENT_RELEASE_VERSION=5.7.2
++ mktemp -d
+ tmpdir=/tmp/tmp.9GqdW2Thr3
+ trap 'rm -rf /tmp/tmp.9GqdW2Thr3' EXIT
+ render /home/ctran/signalfx-agent/deployments/k8s false
+ local outdir=/home/ctran/signalfx-agent/deployments/k8s
+ local isServerless=false
+ helm template signalfx-agent --namespace signalfx-agent --set signalFxAccessToken=MY_TOKEN --set clusterName=MY-CLUSTER --set fullnameOverride=signalfx-agent --set agentVersion=5.7.2 --set isServerless=false --output-dir /tmp/tmp.9GqdW2Thr3 /home/ctran/signalfx-agent/deployments/k8s/helm/signalfx-agent
Error: stat signalfx-agent: no such file or directory
+ rm -rf /tmp/tmp.9GqdW2Thr3
```

**Comment by keitwb** [comment]
ok, I think it might be a helm version issue.  I'm using helm v3.0.3.  What do you have?

**Comment by chungktran** [comment]
I was using 3.4.0 but the error is the same with 3.0.3. It doesn't matter though. You did it already so it's ok.

``` ➜  signalfx-agent git:(master) alias helm=helm-3.0.3
 ➜  signalfx-agent git:(master) helm version
version.BuildInfo{Version:"v3.0.3", GitCommit:"ac925eb7279f4a6955df663a0128044a8a6b7593", GitTreeState:"clean", GoVersion:"go1.13.6"}
 ➜  signalfx-agent git:(master) ./deployments/k8s/generate-from-helm
+++ dirname ./deployments/k8s/generate-from-helm
++ cd ./deployments/k8s
++ pwd
+ SCRIPT_DIR=/home/ctran/signalfx-agent/deployments/k8s
+ AGENT_CHART_DIR=/home/ctran/signalfx-agent/deployments/k8s/helm/signalfx-agent
++ /home/ctran/signalfx-agent/deployments/k8s/../../scripts/latest-final-release
+ AGENT_RELEASE_VERSION=5.7.2
++ mktemp -d
+ tmpdir=/tmp/tmp.x1YSqUDz8v
+ trap 'rm -rf /tmp/tmp.x1YSqUDz8v' EXIT
+ render /home/ctran/signalfx-agent/deployments/k8s false
+ local outdir=/home/ctran/signalfx-agent/deployments/k8s
+ local isServerless=false
+ helm template signalfx-agent --namespace signalfx-agent --set signalFxAccessToken=MY_TOKEN --set clusterName=MY-CLUSTER --set fullnameOverride=signalfx-agent --set agentVersion=5.7.2 --set isServerless=false --output-dir /tmp/tmp.x1YSqUDz8v /home/ctran/signalfx-agent/deployments/k8s/helm/signalfx-agent
Error: stat signalfx-agent: no such file or directory
+ rm -rf /tmp/tmp.x1YSqUDz8v
```

**Pull request closed without merging**
