### PR TITLE
Update agent build stages to ubuntu:18.04

### PR DESCRIPTION
**Pull request by jchengsfx**

### CODE REVIEW

**Comment by keitwb** [comment]
This seems simple enough.  Did all of the packaging/installer tests run without being skipped?

**Comment by jchengsfx** [comment]
> This seems simple enough. Did all of the packaging/installer tests run without being skipped?

Deb, rpm, and bundle tests ran (along with k8s and integration). Installer, puppet, and chef tests skipped since they only test with remote packages.

**Comment by jchengsfx** [comment]
> Looks good but please do some manual testing on Centos 6 and Ubuntu 16.04 before merging and make sure there isn't anything odd. I can't remember what the issue was last time we tried this but I'm a bit paranoid.

Collectd dies on centos6:
```
time="2019-10-31T19:29:44Z" level=debug msg="Collectd is now starting" collectdInstance=global
time="2019-10-31T19:29:44Z" level=debug msg="Rendering main collectd.conf template" collectdInstance=global context="&{false 40 5 2 500000 400000 notice 10 127.9.8.7 0 /var/run/signalfx-agent/collectd /usr/lib/signalfx-agent false global }"
time="2019-10-31T19:29:44Z" level=debug msg="Wrote file /var/run/signalfx-agent/collectd/global/collectd.conf"
time="2019-10-31T19:29:44Z" level=debug msg="Collectd is now running" collectdInstance=global
time="2019-10-31T19:29:44Z" level=info msg="FATAL: kernel too old" collectdInstance=global
time="2019-10-31T19:29:44Z" level=error msg="Collectd died when it was supposed to be running, restarting..." collectdInstance=global
```

Probably still the same issue as what we saw last year with https://signalfuse.atlassian.net/browse/INT-625.

**Comment by keitwb** [comment]
@jchengsfx can you change the base branch to 5.0-staging?

**Review by jrcamp — APPROVED** [review]

**Review by keitwb — APPROVED** [review]

**Pull request merged**
