### PR TITLE
Add an option to control remote config watch

### PR DESCRIPTION
**Pull request by dloucasfx**
Signed-off-by: Dani Louca <dlouca@splunk.com>

### CODE REVIEW

**Review by keitwb — APPROVED** [review]

**Comment by rmfitzpatrick** [comment]
@dloucasfx of if you merge this so we can have a new release tomorrow (unless it's not time sensitive)

**Comment by dloucasfx** [comment]
@rmfitzpatrick yes, it's ready to be merged by I was hoping to get the CI fixed so we can gave a green PR
@jchengsfx can you confirm that all what's failing is CI infra so we can merge it?

**Comment by rmfitzpatrick** [comment]
I believe the CI failure is a known issue though I'm not sure the proposed workaround is viable for us - https://github.com/jeremylong/DependencyCheck/issues/3307

**Comment by rmfitzpatrick** [comment]
@keitwb I don't believe @jchengsfx has the cycles to release today and I don't have my environment setup (or access).  Would you be able to verify this is ok to land and cut a new release to meet a compliance commitment?

**Comment by dloucasfx** [comment]
I think it's safe to go and merge, but I will wait for the green light from @keitwb

**Comment by rmfitzpatrick** [comment]
@dloucasfx I reran and the job passed (it's waiting for ssh sessions to end).

**Pull request merged**
