### PR TITLE
Add sfx_skip_repo option to ansible

### PR DESCRIPTION
**Pull request by jchengsfx**
For #1628

### CODE REVIEW

**Review by keitwb — CHANGES_REQUESTED** [review]
Is it possible to just detect if the default `sfx_repo_base_url` has been overridden and skip doing the repo in that case?  If it isn't possible this is fine but I'd rather go the other route if possible.

**Comment by savec80** [comment]
Hey,
We use RH Satellite and just overwrite sfx_repo_base_url is not easily achievable if at all because you have hardcoded: "signalfx-agent-rpm" in url as well as name of gpgkey.
Thanks.

**Comment by keitwb** [comment]
Ok, so @savec80 you basically just want it to completely skip out on any repo management whatsoever and just try to install the package `signalfx-agent` in whatever you have preconfigured on the system?

**Comment by savec80** [comment]
yes, that's correct. Adding external repo on isolated host results in broken yum.

**Review by keitwb — APPROVED** [review]

**Pull request merged**
