### PR TITLE
Revisions for apache spark tile

### PR DESCRIPTION
**Pull request by pohannigansfx**
Improved formatting and made nomenclature consistent with standard so prescriptive guidance is more apparent. This does not use new jinja template because some of it is generated in Smart Agent repo.

### CODE REVIEW

**Review by tmorrisonsfx — APPROVED** [review]
LGTM

**Comment by pohannigansfx** [comment]
@asuresh4 or @mstumpfx, if either of you has a few minutes for an easy review, I need code owner approval before I can merge this

**Review by mstumpfx — APPROVED** [review]

**Comment by mstumpfx** [comment]
LGTM @pohannigansfx

**Comment by pohannigansfx** [comment]
Added one more commit to this request to help troubleshoot circleci:docs_test failure on previous version, which has thus far prevented merge with master because passing that check is required (other required tests were already passing).

**Pull request merged**
