### PR TITLE
Change custom to included in docs

### PR DESCRIPTION
**Pull request by jaysfx**
Submitting this separately to keep churn in other PRs down.

* Change metrics table to check metrics that are included by default vs. being ones that are not included
* Use a fancy unicode checkmark
* Remove some unneeded whitelist.json processing

### CODE REVIEW

**Comment by mstumpfx** [comment]
cc @barbara-sfx

**Comment by mstumpfx** [comment]
approved but barbara makes a good point, we should make sure we can use that unicode character in product docs

**Comment by jaysfx** [comment]
@barbara-sfx Yep, I built the docs in the product-docs repo and it renders correctly

**Comment by jaysfx** [comment]
Here's what it looks like:

Screen Shot 2019-03-25 at 6 42 51 PM

**Pull request merged**
