### PR TITLE
Upgrade to Go 1.13.1

### PR DESCRIPTION
**Pull request by keitwb**

### CODE REVIEW

**Comment by keitwb** [comment]
@jchengsfx can you confirm I didn't miss any places where the Go version is referenced?

**Comment by jchengsfx** [comment]
> @jchengsfx can you confirm I didn't miss any places where the Go version is referenced?

Do you want to update `test-services/fakek8s/Dockerfile` and `test-services/expvar/Dockerfile`?

**Comment by keitwb** [comment]
> > @jchengsfx can you confirm I didn't miss any places where the Go version is referenced?
> 
> Do you want to update `test-services/fakek8s/Dockerfile` and `test-services/expvar/Dockerfile`?

No, they don't really matter.

**Comment by jchengsfx** [comment]
@keitwb Do we need to invalidate the `go mod download` cache in CI and the agent image?

**Comment by keitwb** [comment]
> @keitwb Do we need to invalidate the `go mod download` cache in CI and the agent image?

I forgot to run `go mod tidy` on the commit.  That will change the go.mod file to include the new go version.  Doign that now.

**Pull request merged**
