### PR TITLE
Move some packages from internal to pkg

### PR DESCRIPTION
**Pull request by captncraig**
This is my attempt to implement the changes I proposed in #1115.

I use the following snippet to rename a package and rewrite imports:

```
SFX="\"github.com/signalfx/signalfx-agent"
PKG="monitors"
mkdir -p pkg/$PKG
git mv internal/$PKG/*.go pkg/$PKG
grep -lR "$SFX/internal/$PKG\"" | xargs sed -i "s=$SFX/internal/$PKG\"=$SFX/pkg/$PKG\"=g"
goimports -w -l .
```

Currently I have moved the following packages from `internal` to `pkg`:

- `monitors`
- `core/config`
- `monitors/types`
- `utils`

These are the ones required to implement a simple monitor. More can be moved in the future as needed or requested.

### CODE REVIEW

**Comment by keitwb** [comment]
Thanks @captncraig.  This is something that I've figured would need to happen someday so thanks for doing it!

Looks like the monitor code gen binary is dependent on non-local agent code based on the error at https://circleci.com/gh/signalfx/signalfx-agent/196587?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link.  I will fix it and push it to this branch.

**Comment by captncraig** [comment]
I think I figured out how to regen the docs properly. Fingers crossed.

**Comment by captncraig** [comment]
@keitwb I see the circleci failure you are talking about now. I am definitely not sure how to fix it.

**Comment by keitwb** [comment]
> @keitwb I see the circleci failure you are talking about now. I am definitely not sure how to fix it.

Yes, will take a look.

I'm also considering just moving everything to `pkg` and not have the split between `internal` and `pkg` but will think about it some more.

**Comment by captncraig** [comment]
> I'm also considering just moving everything to pkg and not have the split between internal and pkg but will think about it some more.

That would certainly be simpler. I assumed things were in internal for a reason, so didn't really want to rock that too hard. Keeping things in internal is a little nice because you can make breaking api changes easier, but having a split like I have done also makes things confusing.

**Comment by keitwb** [comment]
Yes, the encapsulation in `internal/` is nice for signifying things that might break but I think the confusion of having things split is not really worth it.  Also others might want to add/extend other aspects of the agent beyond just adding new monitors.

As far as "breaking changes", I would say that we are willing to help out anybody who is trying to do what you are doing but we aren't making any guarantees about compatibility of code in `pkg` between even minor releases of the agent.  The agent's versioning scheme is centered around compatibility of the configuration and MTSs emitted by the agent, and adding another layer of API compatibility would make things excessively inflexible.  In practice, given the history of the packages you would have to touch, I doubt it would break very often or in ways that are difficult to fix up.  Any "breaking changes" to the monitor interface requires us to fix up several dozen monitors, so it isn't something we do often!

**Comment by captncraig** [comment]
I made a branch that completely moves everything:

https://github.com/signalfx/signalfx-agent/compare/master...captncraig:nointernal

For some reason github crashes every time I try to make a pr from it. I have no idea why.

**Comment by keitwb** [comment]
Yeah I've seen crashes when you make a PR that is very big.  I think I've figured out the issue with the build that this PR has.  I'll try making a PR from a separate branch with the agent main package split out and the code generated modules committed.

**Comment by keitwb** [comment]
Ok, I've got it working in a separate branch but I'm running into the same Github limitation, arg!  I'll see if somebody else in the office can make it go through but if not I might have to bypass the PR route.

**Comment by captncraig** [comment]
I wonder if it could be hacked by opening a very simple pr, then pushing more changes into it?

**Comment by keitwb** [comment]
That worked! See https://github.com/signalfx/signalfx-agent/pull/1118.  Going to close this one and continue everything in that PR.

**Pull request closed without merging**
