### PR TITLE
Add sqlserver as an option for the monitor

### PR DESCRIPTION
**Pull request by kaypeter87**
Currently, the documentation states that the supported drivers includes mssql using the Go MSSQL driver package [go-mssqldb](https://github.com/denisenkom/go-mssqldb/) but the conditions in the monitor code only checks for `postgres` and `mysql`. This PR adds the correct value option to use the driver: `sqlserver`.

### CODE REVIEW

**Comment by dloucasfx** [comment]
@kaypeter87 
please rebase, squash all commits into one and update the PR.
Also the CI is failing on the doc_test, make sure to generate the docs and commit the new changes as part of the same commit.
```
make dev-image
make run-dev-image
make signalfx-agent docs
```

**Comment by kaypeter87** [comment]
> @kaypeter87
> please rebase, squash all commits into one and update the PR.
> Also the CI is failing on the doc_test, make sure to generate the docs and commit the new changes as part of the same commit.
> 
> ```
> make dev-image
> make run-dev-image
> make signalfx-agent docs
> ```

The `make run-dev-image` is failing and cannot find the container `signalfx-agent-dev`. I was able to successfully create the dev image but haven't had time to troubleshoot the second step. Might be an issue with the `Makefile` ?

**Comment by kaypeter87** [comment]
> > @kaypeter87
> > please rebase, squash all commits into one and update the PR.
> > Also the CI is failing on the doc_test, make sure to generate the docs and commit the new changes as part of the same commit.
> > ```
> > make dev-image
> > make run-dev-image
> > make signalfx-agent docs
> > ```
> 
> Thanks for the reply @dloucasfx, but the `make run-dev-image` is failing and cannot find the container `signalfx-agent-dev`. I was able to successfully create the dev image but haven't had time to troubleshoot the second step. Might be an issue with the `Makefile` ?

Had time to go through the make docs steps. Seems the `No container found` error was just a false-positive. I was able to shell into the container and generate the docs.

**Comment by keitwb** [comment]
Thanks for this @kaypeter87.

**Pull request merged**
