### PR TITLE
Cleanup patch for aarch64 support

### PR DESCRIPTION
**Pull request by squishykid**
PR #1436 was a bit of a hack- this achieves the same results without ignoring a magic list of shared objects.

### CODE REVIEW

**Review by MovieStoreGuy — APPROVED** [review]
This is a really neat way to ship support for multiple archs

**Comment by keitwb** [comment]
Ok so basically patchelf 0.11 fixed the corruption issues in the prior version?

**Comment by squishykid** [comment]
Yep, that's it.

**Comment by squishykid** [comment]
I think it might have been fixed in this patch https://github.com/NixOS/patchelf/pull/171

**Comment by MovieStoreGuy** [comment]
@keitwb is this okay to merge? I see the old PR as a code smell and this helps address the actual issue rolling forward without some tribal knowledge hack.

**Pull request merged**
