### PR TITLE
Add the agent pod annotations as values of the Helm chart

### LINKED ISSUE #1129: Helm: ability to add custom annotations to k8s pods
As per [cluster-autoscaler docs](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node), we need to add `"cluster-autoscaler.kubernetes.io/safe-to-evict": "true"` annotation to the pods in order for a node to scale down.
However, it's unable to do so via the current helm charts.
Could we add support for that?

### PR DESCRIPTION
**Pull request by jyrivallan**
It is fairly commonplace to let users change these values in helm charts.

Fixes #1129.

### CODE REVIEW

**Comment by keitwb** [comment]
Thanks for this @jyrivallan!

**Comment by jyrivallan** [comment]
Thank _you_ @keitwb  🙏 
Do you think this will be released soon?

**Comment by keitwb** [comment]
@jyrivallan I released it as Chart version 0.7.1.

**Comment by jyrivallan** [comment]
@keitwb Thanks a lot!
Seems like it's not available in the repo yet
This is what I get when browsing to https://dl.signalfx.com/helm-repo:
```
<Error>
<script>
(function(){EventTarget.prototype.ol_originalAddEventListener=EventTarget.prototype.addEventListener,EventTarget.prototype.addEventListener=function(t,e){var n=this,r=arguments.length>2&&void 0!==arguments[2]&&arguments[2];this.ol_originalAddEventListener(t,e,r),"click"===t&&setTimeout((function(){!window.OL_NOT_LOGIN_PAGE&&n.setAttribute&&n.setAttribute("data-ol-has-click-handler","")}),0)}})("")
</script>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>D1EC20CF3AF4A3B2</RequestId>
<HostId>
yurwl8jVXgIQSP/0ovcP55oi0+2ZR44FF+1oLwAob0R3yMuUbx15UCDQVu8K+7ca12Kd2//TPS8=
</HostId>
</Error>
```

**Comment by keitwb** [comment]
Try it again @jyrivallan, I invalidated the cloudfront cache in front of the s3 bucket we store the Helm chart in.  Also, you can't list the helm-repo directory due to s3 permissions but you should be able to see all of the available versions with `helm search repo signalfx-agent -l` (I'm using Helm 3, so Helm 2 command might be different).

**Comment by jyrivallan** [comment]
Still no luck: 
```
$ helm search repo signalfx-agent -l
NAME                   	CHART VERSION	APP VERSION	DESCRIPTION
signalfx/signalfx-agent	0.7.0        	4.18.3     	The SignalFx Smart Agent
signalfx/signalfx-agent	0.6.1        	4.18.3     	The SignalFx Smart Agent
signalfx/signalfx-agent	0.6.0        	4.14.1     	The SignalFx Smart Agent
signalfx/signalfx-agent	0.5.1        	4.14.0     	The SignalFx Smart Agent
signalfx/signalfx-agent	0.5.0        	4.13.0     	The SignalFx Smart Agent
signalfx/signalfx-agent	0.4.4        	4.13.0     	The SignalFx Smart Agent
signalfx/signalfx-agent	0.4.3        	4.13.0     	The SignalFx Smart Agent
signalfx/signalfx-agent	0.4.2        	4.8.0      	The SignalFx Smart Agent
signalfx/signalfx-agent	0.4.1        	4.7.8      	The SignalFx Smart Agent
signalfx/signalfx-agent	0.3.8        	4.5.0      	The SignalFx Smart Agent
signalfx/signalfx-agent	0.3.5        	4.3.3      	The SignalFx Smart Agent
signalfx/signalfx-agent	0.3.4        	4.3.0      	The SignalFx Smart Agent
signalfx/signalfx-agent	0.3.3        	3.10.0     	The SignalFx Smart Agent
stable/signalfx-agent  	0.3.1        	3.6.1      	DEPRECATED The SignalFx Kubernetes agent
stable/signalfx-agent  	0.3.0        	3.6.1      	The SignalFx Kubernetes agent
stable/signalfx-agent  	0.2.1        	3.2.2      	The SignalFx Kubernetes agent
stable/signalfx-agent  	0.2.0        	3.1.9      	The SignalFx Kubernetes agent
stable/signalfx-agent  	0.1.1        	3.1.9      	The SignalFx Kubernetes agent
stable/signalfx-agent  	0.1.0        	3.0.0      	The SignalFx Kubernetes agent
```

(after a `helm repo update` - I'm running Helm 3.1.0)

**Comment by keitwb** [comment]
Ok, try again.  I think the CloudFront invalidation was just taking a long time to propagate, I confirmed it has invalidated for servers in the US, might take a bit longer for Europe.

**Comment by jyrivallan** [comment]
@keitwb It did work indeed. Thanks again 🙏

**Pull request merged**
