### PR TITLE
Update telegraf fork and gopsutil versions

### PR DESCRIPTION
**Pull request by rmfitzpatrick**
Incorporates gopsutil updates from https://github.com/signalfx/signalfx-agent/pull/1551 and https://github.com/signalfx/telegraf/pull/23

### CODE REVIEW

**Review by keitwb — APPROVED** [review]
Looks good but Windows tests need to pass before it can be merged.

**Comment by keitwb** [comment]
Looks like some compile issue with the new telegraf.

**Review by keitwb — CHANGES_REQUESTED** [review]
See comments.

**Comment by dloucasfx** [comment]
I just want to note that I am working on a bunch of performance issues that are directly related to our dated gopsutil version, this upgrade will be a great help and we needed out as soon as possible

**Review by keitwb — APPROVED** [review]
Change looks good, just make sure all tests pass and it's good to go.

**Comment by rmfitzpatrick** [comment]
@keitwb @dloucasfx this required more changes in our telegraf fork than I anticipated.  Once CI clears here, I'll open a corresponding PR in that project and once it lands update the target pseudoversion in this lib to match.

**Comment by rmfitzpatrick** [comment]
> I just want to note that I am working on a bunch of performance issues that are directly related to our dated gopsutil version, this upgrade will be a great help and we needed out as soon as possible

Good to hear @dloucasfx, will be sure to update to the resulting merge commit from https://github.com/signalfx/telegraf/pull/24

**Comment by rmfitzpatrick** [comment]
https://github.com/signalfx/telegraf/commit/57d1c187171a20663bfe8433c6d073ce51b3f182 broken windows tests so I've reverted in our fork.

**Pull request merged**
