### PR TITLE
#1399 add varnish telegraf based monitor

### PR DESCRIPTION
**Pull request by xp-1000**
hello
this should address https://github.com/signalfx/signalfx-agent/issues/1399 and more.
tested on varnish 5 and 6.

### CODE REVIEW

**Comment by xp-1000** [comment]
Hello @keitwb 

honnestly I don't know why intergrations tests failed here, I run it multiple times on my laptop and it works fine: 

```
[gw5] [ 94%] PASSED tests/monitors/telegraf_varnish/varnish_test.py::test_telegraf_varnish_metrics 
```

could you re run the CI ?

**Comment by keitwb** [comment]
> Hello @keitwb
> 
> honnestly I don't know why intergrations tests failed here, I run it multiple times on my laptop and it works fine:
> 
> ```
> [gw5] [ 94%] PASSED tests/monitors/telegraf_varnish/varnish_test.py::test_telegraf_varnish_metrics 
> ```
> 
> could you re run the CI ?

I suspect you have `/usr/bin/varnishstat` installed on your laptop.  You made a function to run a varnish container but aren't ever running it.  Even if you did, it seems unreachable by the telegraf/varnish code since it assumes that varnish is running on the same host/namespace as the agent (I don't see any config for host or port, only the varnishstat binary path and instance name).  I'm open to this monitor but it seems to have sever restrictions and doesn't appear to possibly work in a containered environment at all.

**Comment by xp-1000** [comment]
> > Hello @keitwb
> > honnestly I don't know why intergrations tests failed here, I run it multiple times on my laptop and it works fine:
> > ```
> > [gw5] [ 94%] PASSED tests/monitors/telegraf_varnish/varnish_test.py::test_telegraf_varnish_metrics 
> > ```
> > 
> > 
> > could you re run the CI ?
> 
> I suspect you have `/usr/bin/varnishstat` installed on your laptop. You made a function to run a varnish container but aren't ever running it. Even if you did, it seems unreachable by the telegraf/varnish code since it assumes that varnish is running on the same host/namespace as the agent (I don't see any config for host or port, only the varnishstat binary path and instance name). I'm open to this monitor but it seems to have sever restrictions and doesn't appear to possibly work in a containered environment at all.

you are right @keitwb, it was late yesterday and I did a mess ^^ 

I will need the varnish package installed where the tests are run (and the varnish should be started obviously).

**Comment by xp-1000** [comment]
@keitwb I am not sure I can update the docker dev image myself and the only way I see to pass tests is to install varnish package in dev image. I updated the Dockerfile.dev for local dev usage but I see circle ci uses image from quay.io which should be updated no ?

**Comment by keitwb** [comment]
You can install it in https://github.com/signalfx/signalfx-agent/blob/master/.circleci/scripts/setup-integration-tests.sh but you will still have the issue of how to get varnishstat to talk to a varnish instance in the container.  You could run varnish straight on the CI box outside a container but I would rather not if possible.  I think when I checked how it works before it does some stuff with a shared memory block or something, so it might be tough.

**Comment by xp-1000** [comment]
> You can install it in https://github.com/signalfx/signalfx-agent/blob/master/.circleci/scripts/setup-integration-tests.sh but you will still have the issue of how to get varnishstat to talk to a varnish instance in the container. You could run varnish straight on the CI box outside a container but I would rather not if possible. I think when I checked how it works before it does some stuff with a shared memory block or something, so it might be tough.

yes, it seems little tricky, do you think can we omit tests exceptionally for this monitor @keitwb ?

**Comment by keitwb** [comment]
Yes, that's fine.  We already know the telegraf shim and the telegraf plugin works from existing tests so as long as you are confident in the operation of it for your needs it should be fine.

**Comment by xp-1000** [comment]
sorry @keitwb I see the following error on go-lint:

```
level=warning msg="[runner] Can't run linter unused: buildssa: analysis skipped: errors in package: [/__w/1/s/pkg/monitors/telegraf/monitors/varnish/varnish.go:53:64: Varnish not declared by package varnish]"
```

I confess it is not obvious for me may be it speak to you ? else I will check that tomorrow ;)

**Comment by keitwb** [comment]
The linter failure was on Windows.  Apparently that plugin isn't supported on Windows in Telegraf, so it can't be in the agent either.  I disabled it building on Windows.

**Comment by xp-1000** [comment]
hello @keitwb, me again ^^ could you just confirm the ci failed is not due to my changes ? or do i still have things to do?

**Comment by keitwb** [comment]
Yes, CI failures are some random other thing.  Looks good.  Thanks for submitting this.

**Pull request merged**
